// ── ScreenMap — the agent's view of every navigable screen ──────────────────
//
// The TagAI agent uses this map to plan navigation. The model can call
// `list_screens(role|query)` to see what's available, or `get_screen_info(name)`
// to drill into one screen's components, tap targets, and tools that work
// against it.
//
// Each entry contains:
//   - name:        the route name (matches `Stack.Screen name=` in App.js)
//   - role:        "customer" | "seller" | "both" (seller screens also live
//                  in this app — they're rendered inside AccountScreen when
//                  the user has a seller record).
//   - label:       human-readable name for chat
//   - description: 1-line what-it-does
//   - contains:    list of common components/elements the screen shows
//   - tapTargets:  list of stable item-ids registered by the screen that
//                  the `tap_element` tool can invoke.
//   - tools:       list of agent tools most useful on this screen
//   - params:      expected route params
//   - children:    for parent screens, sub-screens and a one-liner each
//
// IMPORTANT: when you add a new screen to App.js, also add it here so the
// agent can navigate to it.

export const SCREEN_MAP = {
  // ── Customer screens ────────────────────────────────────────────────────
  Main: {
    name: "Main",
    role: "customer",
    label: "Home tabs",
    description: "The bottom tab bar — Home, Chats, Feed, Cart, Account.",
    contains: [
      "Tab bar (Home, Chats, Feed, Cart, Account)",
      "TagAI button (floating, opens chat)",
    ],
    tapTargets: ["tagAI.inputBar"],
    tools: ["navigate_to_page", "point_to_element", "read_screen"],
    params: { screen: "Home|Chats|Feed|Cart|Account" },
    children: {
      Home: "The home feed (recommended products, categories, ads, search).",
      Chats: "The list of customer and seller conversations.",
      Feed: "The vertical reels feed (product videos, comments, follows).",
      Cart: "The shopping cart (line items, totals, checkout button).",
      Account: "Your profile, settings, and (if a seller) the seller admin.",
    },
  },
  Auth: {
    name: "Auth",
    role: "customer",
    label: "Sign in / sign up",
    description: "Email or phone authentication, with redirect support.",
    contains: ["Email/phone input", "Continue button", "Forgot password link"],
    tapTargets: ["auth.continue", "auth.forgotPassword"],
    tools: ["navigate_to_page", "point_to_element", "read_screen"],
    params: { redirectTo: "string", redirectParams: "object" },
  },
  ForgotPassword: {
    name: "ForgotPassword",
    role: "customer",
    label: "Forgot password",
    description: "Email-based password reset.",
    contains: ["Email input", "Send reset link button"],
    tapTargets: ["forgotPassword.submit"],
    tools: ["navigate_to_page", "read_screen"],
    params: {},
  },
  ResetPassword: {
    name: "ResetPassword",
    role: "customer",
    label: "Reset password",
    description: "Set a new password after a reset email link.",
    contains: ["New password input", "Confirm input", "Submit button"],
    tapTargets: ["resetPassword.submit"],
    tools: ["navigate_to_page", "read_screen"],
    params: {},
  },
  Search: {
    name: "Search",
    role: "customer",
    label: "Search",
    description: "Free-text product/store search with suggestions.",
    contains: [
      "Search input",
      "Recent searches",
      "Trending searches",
      "Suggestion chips",
    ],
    tapTargets: ["search.input", "search.suggestion"],
    tools: ["search_products", "search_stores", "navigate_to_page", "read_screen"],
    params: {},
  },
  SearchResults: {
    name: "SearchResults",
    role: "customer",
    label: "Search results",
    description: "Product/filter results list or grid.",
    contains: ["Result list", "Inline ads", "Pagination"],
    tapTargets: ["searchResults.filter", "searchResults.sort"],
    tools: [
      "search_products",
      "filter_catalog",
      "navigate_to_product",
      "navigate_to_store",
      "add_to_cart",
      "read_screen",
      "scroll",
    ],
    params: { query: "string?", tag: "string?", categoryId: "string?" },
  },
  Categories: {
    name: "Categories",
    role: "customer",
    label: "Categories",
    description: "Browse all categories.",
    contains: ["Category grid"],
    tapTargets: [],
    tools: ["navigate_to_page", "read_screen"],
    params: {},
  },
  CategoryProducts: {
    name: "CategoryProducts",
    role: "customer",
    label: "Category products",
    description: "All products in a single category.",
    contains: ["Product grid", "Sort + filter chips"],
    tapTargets: ["categoryProducts.filter", "categoryProducts.sort"],
    tools: [
      "filter_catalog",
      "navigate_to_product",
      "add_to_cart",
      "read_screen",
      "scroll",
    ],
    params: { categoryId: "string" },
  },
  Stores: {
    name: "Stores",
    role: "customer",
    label: "Stores",
    description: "Browse all stores.",
    contains: ["Store list (with rating, location, badges)"],
    tapTargets: [],
    tools: ["search_stores", "navigate_to_store", "read_screen", "scroll"],
    params: {},
  },
  Store: {
    name: "Store",
    role: "customer",
    label: "Store profile",
    description: "A single seller's storefront — products, info, follow.",
    contains: [
      "Store header (avatar, cover, name, rating, badges)",
      "About / store description",
      "Store policies",
      "Product grid",
      "Follow / message buttons",
      "Social links",
    ],
    tapTargets: [
      "store.follow",
      "store.message",
      "store.products.filter",
      "store.products.sort",
    ],
    tools: [
      "get_store_details",
      "get_store_products",
      "get_store_reviews",
      "navigate_to_product",
      "add_to_cart",
      "read_screen",
      "scroll",
    ],
    params: { sellerId: "string" },
  },
  ProductDetail: {
    name: "ProductDetail",
    role: "customer",
    label: "Product detail",
    description: "Single product page — images, specs, reviews, add to cart.",
    contains: [
      "Image gallery",
      "Price + discount",
      "Title + rating",
      "Size / color / variant pickers",
      "Quantity stepper",
      "Add to cart button",
      "Buy now button",
      "Store card (link to store)",
      "Specifications (key/value)",
      "Tags",
      "Reviews (with stars + comments)",
      "Chat with seller button",
      "Share / report",
    ],
    tapTargets: [
      "productDetail.addToCart",
      "productDetail.buyNow",
      "productDetail.size",
      "productDetail.color",
      "productDetail.quantity",
      "productDetail.openStore",
      "productDetail.chatSeller",
      "productDetail.readMoreReviews",
      "productDetail.helpfulReview",
    ],
    tools: [
      "get_product_details",
      "get_product_reviews",
      "get_store_details",
      "add_to_cart",
      "navigate_to_store",
      "point_to_element",
      "read_screen",
      "scroll",
    ],
    params: { productId: "string" },
  },
  Chat: {
    name: "Chat",
    role: "customer",
    label: "Chat with seller",
    description: "1-on-1 conversation with a seller about a product.",
    contains: [
      "Message thread",
      "Input bar (text + send button)",
      "Product / seller context card",
    ],
    tapTargets: ["chat.input", "chat.send", "chat.attachment"],
    tools: ["navigate_to_page", "read_screen", "scroll"],
    params: { seller: "object", product: "object?" },
  },
  Chats: {
    name: "Chats",
    role: "customer",
    label: "Conversations",
    description: "List of all conversations (customer + seller).",
    contains: ["Conversation list", "Search bar", "Status / story strip"],
    tapTargets: ["chats.search", "chats.open"],
    tools: ["navigate_to_page", "read_screen", "scroll"],
    params: {},
  },
  SellerChat: {
    name: "SellerChat",
    role: "seller",
    label: "Seller chat",
    description: "Chat thread from the seller's perspective.",
    contains: ["Message thread", "Input bar", "Customer context card"],
    tapTargets: ["sellerChat.input", "sellerChat.send"],
    tools: ["navigate_to_page", "read_screen", "scroll"],
    params: { conversationId: "string", customer: "object" },
  },
  StatusViewer: {
    name: "StatusViewer",
    role: "customer",
    label: "Status viewer",
    description: "Full-screen viewer for a seller's status/story.",
    contains: ["Progress bar", "Seller header", "Story content", "Reply input"],
    tapTargets: ["statusViewer.reply"],
    tools: ["navigate_to_page", "read_screen"],
    params: { sellerId: "string" },
  },
  StatusCreator: {
    name: "StatusCreator",
    role: "seller",
    label: "Create status",
    description: "Sellers post a new status/story from here.",
    contains: [
      "Mode picker (image vs text)",
      "Image picker",
      "Caption input",
      "Post button",
    ],
    tapTargets: [
      "statusCreator.image",
      "statusCreator.text",
      "statusCreator.caption",
      "statusCreator.post",
    ],
    tools: ["navigate_to_page", "read_screen"],
    params: {},
  },
  StoreRegistration: {
    name: "StoreRegistration",
    role: "customer",
    label: "Become a seller",
    description: "Apply to open a new store.",
    contains: [
      "Store name input",
      "Description input",
      "Category picker",
      "Submit application",
    ],
    tapTargets: ["storeRegistration.submit"],
    tools: ["navigate_to_page", "read_screen"],
    params: {},
  },
  Checkout: {
    name: "Checkout",
    role: "customer",
    label: "Checkout",
    description: "Final review, addresses, promo, payment.",
    contains: [
      "Cart line items",
      "Address picker",
      "Promo code input + apply",
      "Order summary",
      "Pay now button",
    ],
    tapTargets: [
      "checkout.promoCode",
      "checkout.applyPromo",
      "checkout.address",
      "checkout.payButton",
      "checkout.orderSummary",
    ],
    tools: ["navigate_to_page", "read_screen", "scroll", "point_to_element"],
    params: {},
  },
  PaymentWebView: {
    name: "PaymentWebView",
    role: "customer",
    label: "Payment gateway",
    description: "Paystack web view that handles card / mobile-money payment.",
    contains: ["WebView (full screen)"],
    tapTargets: [],
    tools: ["navigate_to_page"],
    params: { payment: "object" },
  },
  Orders: {
    name: "Orders",
    role: "customer",
    label: "Orders",
    description: "List of past and in-flight orders.",
    contains: ["Order list", "Status filter chips"],
    tapTargets: ["orders.filter", "orders.row"],
    tools: ["navigate_to_page", "read_screen", "scroll"],
    params: {},
  },
  OrderDetail: {
    name: "OrderDetail",
    role: "customer",
    label: "Order detail",
    description: "Single order — items, status, tracking, totals.",
    contains: [
      "Order header",
      "Line items",
      "Shipping info",
      "Totals",
      "Action buttons (cancel, reorder, contact seller)",
    ],
    tapTargets: ["orderDetail.cancel", "orderDetail.reorder", "orderDetail.contact"],
    tools: ["navigate_to_page", "read_screen", "scroll"],
    params: { orderId: "string" },
  },
  OrderSuccess: {
    name: "OrderSuccess",
    role: "customer",
    label: "Order placed",
    description: "Confirmation page after a successful checkout.",
    contains: ["Success animation", "Order summary", "Continue button"],
    tapTargets: ["orderSuccess.continue"],
    tools: ["navigate_to_page", "read_screen"],
    params: {},
  },
  Collections: {
    name: "Collections",
    role: "customer",
    label: "Collections",
    description:
      "Your saved-product collections. Tap a collection to see its items, or create a new one inline.",
    contains: [
      "Collection list",
      "New-collection form",
      "Pull-to-refresh",
    ],
    tapTargets: ["collections.row", "collections.create"],
    tools: ["navigate_to_page", "read_screen", "scroll"],
    params: {},
  },
  CollectionDetail: {
    name: "CollectionDetail",
    role: "customer",
    label: "Collection detail",
    description: "Products inside a single collection.",
    contains: ["Product grid", "Add-to-cart action", "Remove action"],
    tapTargets: ["collectionDetail.row"],
    tools: [
      "navigate_to_product",
      "add_to_cart",
      "navigate_to_page",
      "read_screen",
      "scroll",
    ],
    params: {
      collectionId: "string (UUID)",
      collectionName: "string",
    },
  },
  Notifications: {
    name: "Notifications",
    role: "customer",
    label: "Notifications",
    description: "In-app notification list.",
    contains: ["Notification list"],
    tapTargets: ["notifications.row"],
    tools: ["navigate_to_page", "read_screen", "scroll"],
    params: {},
  },
  Addresses: {
    name: "Addresses",
    role: "customer",
    label: "Addresses",
    description: "Manage shipping addresses.",
    contains: ["Address list", "Add new button"],
    tapTargets: ["addresses.add", "addresses.edit", "addresses.delete"],
    tools: ["navigate_to_page", "read_screen", "scroll"],
    params: {},
  },
  Payments: {
    name: "Payments",
    role: "customer",
    label: "Payments",
    description: "Saved payment methods (cards, mobile money).",
    contains: ["Payment method list", "Add new button"],
    tapTargets: ["payments.add", "payments.setDefault"],
    tools: ["navigate_to_page", "read_screen", "scroll"],
    params: {},
  },
  Following: {
    name: "Following",
    role: "customer",
    label: "Following",
    description: "Stores you follow.",
    contains: ["Store list (followed)"],
    tapTargets: ["following.row"],
    tools: ["navigate_to_store", "read_screen", "scroll"],
    params: {},
  },
  Settings: {
    name: "Settings",
    role: "both",
    label: "Settings",
    description: "Theme, language, notifications, privacy, security.",
    contains: [
      "Theme picker",
      "Notification preferences",
      "Privacy link",
      "Security link",
    ],
    tapTargets: [
      "settings.theme",
      "settings.notifications",
      "settings.privacy",
      "settings.security",
      "settings.signOut",
    ],
    tools: ["navigate_to_page", "read_screen", "scroll", "point_to_element"],
    params: {},
  },
  Security: {
    name: "Security",
    role: "both",
    label: "Security",
    description: "Change password, change email, 2FA, sign-out.",
    contains: [
      "Change password button",
      "Change email button",
      "Sign out button",
    ],
    tapTargets: [
      "security.changePassword",
      "security.changeEmail",
      "security.signOut",
    ],
    tools: ["navigate_to_page", "read_screen", "scroll"],
    params: {},
  },
  HelpSupport: {
    name: "HelpSupport",
    role: "both",
    label: "Help & support",
    description: "FAQs, contact, ticket form.",
    contains: ["FAQ list", "Contact button", "Submit ticket form"],
    tapTargets: ["helpSupport.contact", "helpSupport.submit"],
    tools: ["navigate_to_page", "read_screen", "scroll"],
    params: {},
  },
  Terms: {
    name: "Terms",
    role: "both",
    label: "Terms of service",
    description: "Read-only terms page.",
    contains: ["Terms text"],
    tapTargets: [],
    tools: ["navigate_to_page", "read_screen", "scroll"],
    params: {},
  },
  ProfileEdit: {
    name: "ProfileEdit",
    role: "both",
    label: "Edit profile",
    description: "Edit your name, avatar, bio.",
    contains: ["Name input", "Avatar picker", "Bio input", "Save button"],
    tapTargets: [
      "profileEdit.avatar",
      "profileEdit.name",
      "profileEdit.bio",
      "profileEdit.save",
    ],
    tools: ["navigate_to_page", "read_screen", "scroll"],
    params: {},
  },
  SellerProfile: {
    name: "SellerProfile",
    role: "seller",
    label: "Store profile (edit)",
    description: "Edit your seller profile — name, description, theme, socials.",
    contains: [
      "Avatar picker",
      "Cover image picker",
      "Name input",
      "Bio input",
      "Description input",
      "Social links",
      "Theme color",
      "Save button",
    ],
    tapTargets: [
      "sellerProfile.avatar",
      "sellerProfile.cover",
      "sellerProfile.name",
      "sellerProfile.bio",
      "sellerProfile.theme",
      "sellerProfile.save",
    ],
    tools: ["navigate_to_page", "read_screen", "scroll"],
    params: {},
  },
  ChangePassword: {
    name: "ChangePassword",
    role: "both",
    label: "Change password",
    description: "Enter current + new password.",
    contains: ["Current input", "New input", "Confirm input", "Save button"],
    tapTargets: [
      "changePassword.current",
      "changePassword.new",
      "changePassword.save",
    ],
    tools: ["navigate_to_page", "read_screen"],
    params: {},
  },
  ChangeEmail: {
    name: "ChangeEmail",
    role: "both",
    label: "Change email",
    description: "Update your email address.",
    contains: ["Email input", "Save button"],
    tapTargets: ["changeEmail.save"],
    tools: ["navigate_to_page", "read_screen"],
    params: {},
  },
  PrivacySettings: {
    name: "PrivacySettings",
    role: "both",
    label: "Privacy settings",
    description: "Block list, hidden stores, data sharing toggles.",
    contains: ["Block list", "Hidden stores", "Toggle rows"],
    tapTargets: ["privacySettings.unhide", "privacySettings.toggle"],
    tools: ["navigate_to_page", "read_screen", "scroll"],
    params: {},
  },
  PrivacyPolicy: {
    name: "PrivacyPolicy",
    role: "both",
    label: "Privacy policy",
    description: "Read-only policy text.",
    contains: ["Policy text"],
    tapTargets: [],
    tools: ["navigate_to_page", "read_screen", "scroll"],
    params: {},
  },
  TagAI: {
    name: "TagAI",
    role: "both",
    label: "TagAI assistant",
    description: "The in-app AI assistant (this chat).",
    contains: [
      "Message list",
      "Product cards",
      "Tool chips",
      "Input bar",
      "Thinking trace panel",
    ],
    tapTargets: ["tagAI.inputBar", "tagAI.send", "tagAI.suggestion"],
    tools: [
      "search_products",
      "filter_catalog",
      "get_product_details",
      "get_product_reviews",
      "get_store_details",
      "get_store_products",
      "get_store_reviews",
      "search_stores",
      "add_to_cart",
      "navigate_to_page",
      "navigate_to_product",
      "navigate_to_store",
      "point_to_element",
      "list_screens",
      "get_screen_info",
      "tap_element",
      "scroll",
      "read_screen",
      "wait_for",
      "get_app_state",
      "dismiss_overlay",
    ],
    params: {},
  },
  // Pseudo-screen — the in-app seller admin. It's not a separate
  // Stack.Screen; AccountScreen renders <SellerAdminScreen /> when the
  // user has a seller record. We still surface it here so the agent can
  // ask "open the seller dashboard" and the dispatcher knows how to find
  // it.
  SellerAdmin: {
    name: "SellerAdmin",
    role: "seller",
    label: "Seller dashboard",
    description:
      "In-app seller admin: catalog, orders, stats, products, flash sales. Reached via Account → your store.",
    contains: [
      "Dashboard stats (orders, revenue, ratings)",
      "Catalog (grid / list of your products)",
      "Orders (pending, packed, shipped, delivered)",
      "Marketing (flash sales, ads, coupons)",
      "Reviews (your product reviews)",
      "Add product button",
      "Go-live toggle",
      "Product edit modal (price, stock, specs, images, video)",
    ],
    tapTargets: [
      "sellerAdmin.addProduct",
      "sellerAdmin.goLive",
      "sellerAdmin.tab.dashboard",
      "sellerAdmin.tab.catalog",
      "sellerAdmin.tab.orders",
      "sellerAdmin.tab.marketing",
      "sellerAdmin.tab.reviews",
      "sellerAdmin.productRow",
      "sellerAdmin.editProduct",
      "sellerAdmin.openStorefront",
    ],
    tools: [
      "get_product_details",
      "get_product_reviews",
      "get_store_details",
      "get_store_reviews",
      "get_app_state",
      "read_screen",
      "scroll",
      "tap_element",
      "point_to_element",
    ],
    params: {},
  },
};

/** Return the curated list, optionally filtered by role or query. */
export const listScreens = ({ role, query } = {}) => {
  const all = Object.values(SCREEN_MAP);
  return all.filter((s) => {
    if (role && role !== "both" && s.role !== role && s.role !== "both")
      return false;
    if (query) {
      const q = String(query).toLowerCase();
      const haystack =
        `${s.name} ${s.label} ${s.description} ${(s.tapTargets || []).join(
          " ",
        )}`.toLowerCase();
      if (!haystack.includes(q)) return false;
    }
    return true;
  });
};

/** Look up a single screen by name. */
export const getScreenInfo = (name) => {
  if (!name) return null;
  return SCREEN_MAP[name] || null;
};
