-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.express_profiles (
  id uuid NOT NULL,
  email text NOT NULL,
  full_name text,
  phone text,
  avatar_url text,
  role USER-DEFINED NOT NULL DEFAULT 'customer'::user_role,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  push_token text,
  notification_preferences jsonb DEFAULT '{"chat": true, "orders": true, "marketing": false}'::jsonb,
  last_seen_at timestamp with time zone,
  CONSTRAINT express_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT express_profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.express_categories (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL UNIQUE,
  slug text UNIQUE,
  icon text,
  color text,
  image_url text,
  parent_id uuid,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT express_categories_pkey PRIMARY KEY (id),
  CONSTRAINT express_categories_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.express_categories(id)
);
CREATE TABLE public.express_sellers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  name text NOT NULL UNIQUE,
  slug text UNIQUE,
  email text NOT NULL,
  phone text,
  avatar text,
  cover_image text,
  description text,
  location text,
  address jsonb DEFAULT '{}'::jsonb,
  rating numeric DEFAULT 0 CHECK (rating >= 0::numeric AND rating <= 5::numeric),
  total_ratings integer DEFAULT 0,
  fulfillment_speed text,
  weekly_target numeric,
  commission_rate numeric DEFAULT 10.00,
  is_verified boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  badges ARRAY DEFAULT '{}'::text[],
  social_facebook text,
  social_instagram text,
  social_twitter text,
  social_whatsapp text,
  social_website text,
  theme_color text DEFAULT '#2563EB'::text,
  theme_apply_store boolean DEFAULT false,
  theme_apply_customer boolean DEFAULT false,
  payment_account text,
  account_code text,
  payment_platform text,
  payment_provider text,
  payment_currency text,
  default_shipping_fee numeric DEFAULT 0,
  last_seen_at timestamp with time zone,
  account_verified boolean NOT NULL DEFAULT false,
  store_description text,
  CONSTRAINT express_sellers_pkey PRIMARY KEY (id),
  CONSTRAINT express_sellers_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.express_products (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  seller_id uuid,
  vendor text,
  title text NOT NULL,
  slug text,
  description text,
  price numeric NOT NULL DEFAULT 0 CHECK (price >= 0::numeric),
  compare_at_price numeric CHECK (compare_at_price IS NULL OR compare_at_price >= 0::numeric),
  cost_price numeric CHECK (cost_price IS NULL OR cost_price >= 0::numeric),
  discount numeric DEFAULT 0 CHECK (discount >= 0::numeric AND discount <= 100::numeric),
  sku text,
  barcode text,
  quantity integer DEFAULT 0 CHECK (quantity >= 0),
  track_inventory boolean DEFAULT true,
  allow_backorder boolean DEFAULT false,
  weight numeric,
  weight_unit text DEFAULT 'kg'::text,
  rating numeric DEFAULT 0 CHECK (rating >= 0::numeric AND rating <= 5::numeric),
  total_ratings integer DEFAULT 0,
  badges ARRAY DEFAULT '{}'::text[],
  thumbnail text,
  thumbnails ARRAY DEFAULT '{}'::text[],
  video_url text,
  r2_video_key text,
  category text,
  category_id uuid,
  tags ARRAY DEFAULT '{}'::text[],
  sizes ARRAY DEFAULT '{}'::text[],
  colors ARRAY DEFAULT '{}'::text[],
  variants jsonb DEFAULT '[]'::jsonb,
  specifications jsonb DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['draft'::text, 'pending'::text, 'active'::text, 'rejected'::text, 'archived'::text])),
  rejection_reason text,
  is_featured boolean DEFAULT false,
  view_count integer DEFAULT 0,
  sold_count integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  shipping_fee numeric DEFAULT 0,
  is_preorder boolean NOT NULL DEFAULT false,
  CONSTRAINT express_products_pkey PRIMARY KEY (id),
  CONSTRAINT express_products_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES public.express_sellers(id),
  CONSTRAINT express_products_category_fkey FOREIGN KEY (category) REFERENCES public.express_categories(name),
  CONSTRAINT express_products_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.express_categories(id)
);
CREATE TABLE public.express_addresses (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  label text DEFAULT 'Home'::text,
  full_name text NOT NULL,
  phone text NOT NULL,
  street_address text NOT NULL,
  apartment text,
  city text NOT NULL,
  state text NOT NULL,
  postal_code text,
  country text DEFAULT 'Ghana'::text,
  latitude numeric,
  longitude numeric,
  is_default boolean DEFAULT false,
  delivery_instructions text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT express_addresses_pkey PRIMARY KEY (id),
  CONSTRAINT express_addresses_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.express_wishlists (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  product_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT express_wishlists_pkey PRIMARY KEY (id),
  CONSTRAINT express_wishlists_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT express_wishlists_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.express_products(id)
);
CREATE TABLE public.express_carts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  session_id text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT express_carts_pkey PRIMARY KEY (id),
  CONSTRAINT express_carts_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.express_cart_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  cart_id uuid NOT NULL,
  product_id uuid NOT NULL,
  quantity integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
  size text,
  color text,
  variant_id text,
  price numeric NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT express_cart_items_pkey PRIMARY KEY (id),
  CONSTRAINT express_cart_items_cart_id_fkey FOREIGN KEY (cart_id) REFERENCES public.express_carts(id),
  CONSTRAINT express_cart_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.express_products(id)
);
CREATE TABLE public.express_orders (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  order_number text NOT NULL UNIQUE,
  user_id uuid,
  seller_id uuid,
  vendor text NOT NULL,
  status text NOT NULL DEFAULT 'pending_payment'::text CHECK (status = ANY (ARRAY['pending_payment'::text, 'processing'::text, 'confirmed'::text, 'packed'::text, 'shipped'::text, 'delivered'::text, 'canceled'::text, 'refunded'::text])),
  subtotal numeric NOT NULL DEFAULT 0,
  discount_amount numeric DEFAULT 0,
  service_fee numeric DEFAULT 0,
  tax_amount numeric DEFAULT 0,
  total numeric NOT NULL DEFAULT 0,
  currency text DEFAULT 'NGN'::text,
  customer jsonb DEFAULT '{}'::jsonb,
  shipping_address jsonb DEFAULT '{}'::jsonb,
  billing_address jsonb DEFAULT '{}'::jsonb,
  payment_method text,
  payment_reference text,
  payment_status text DEFAULT 'pending'::text CHECK (payment_status = ANY (ARRAY['pending'::text, 'success'::text, 'failed'::text, 'refunded'::text])),
  paystack_reference text,
  notes text,
  tracking_number text,
  tracking_url text,
  shipped_at timestamp with time zone,
  delivered_at timestamp with time zone,
  canceled_at timestamp with time zone,
  cancellation_reason text,
  eta timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  paid_at timestamp with time zone,
  payment_data jsonb,
  shipping_fee numeric DEFAULT 0,
  service_fee_pct numeric DEFAULT 0,
  CONSTRAINT express_orders_pkey PRIMARY KEY (id),
  CONSTRAINT express_orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT express_orders_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES public.express_sellers(id)
);
CREATE TABLE public.express_order_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  order_id uuid NOT NULL,
  product_id uuid,
  seller_id uuid,
  title text NOT NULL,
  sku text,
  thumbnail text,
  quantity integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
  price numeric NOT NULL DEFAULT 0,
  discount numeric DEFAULT 0,
  total numeric NOT NULL DEFAULT 0,
  size text,
  color text,
  variant_data jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  shipping_fee numeric DEFAULT 0,
  CONSTRAINT express_order_items_pkey PRIMARY KEY (id),
  CONSTRAINT express_order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.express_orders(id),
  CONSTRAINT express_order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.express_products(id),
  CONSTRAINT express_order_items_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES public.express_sellers(id)
);
CREATE TABLE public.express_payments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  order_id uuid,
  user_id uuid,
  amount numeric NOT NULL,
  currency text DEFAULT 'NGN'::text,
  provider text NOT NULL DEFAULT 'paystack'::text,
  reference text NOT NULL UNIQUE,
  authorization_code text,
  channel text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'success'::text, 'failed'::text, 'refunded'::text])),
  gateway_response text,
  metadata jsonb DEFAULT '{}'::jsonb,
  paid_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  paystack_fee_pesewas integer DEFAULT 0,
  paystack_fee_split jsonb,
  service_fee_amount numeric DEFAULT 0,
  platform_commission numeric DEFAULT 0,
  seller_amount numeric,
  platform_amount numeric,
  payment_type text NOT NULL DEFAULT 'order'::text CHECK (payment_type = ANY (ARRAY['order'::text, 'store_registration'::text])),
  seller_id uuid,
  CONSTRAINT express_payments_pkey PRIMARY KEY (id),
  CONSTRAINT express_payments_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.express_orders(id),
  CONSTRAINT express_payments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT express_payments_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES public.express_sellers(id)
);
CREATE TABLE public.express_reviews (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  product_id uuid NOT NULL,
  user_id uuid NOT NULL,
  order_id uuid,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  title text,
  comment text,
  images ARRAY DEFAULT '{}'::text[],
  is_verified_purchase boolean DEFAULT false,
  is_approved boolean DEFAULT false,
  helpful_count integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT express_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT express_reviews_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.express_products(id),
  CONSTRAINT express_reviews_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.express_orders(id),
  CONSTRAINT express_reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.express_profiles(id)
);
CREATE TABLE public.express_support_tickets (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  ticket_number text UNIQUE,
  user_id uuid,
  seller_id uuid,
  order_id uuid,
  vendor text,
  subject text NOT NULL,
  category text,
  status text NOT NULL DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'in_progress'::text, 'resolved'::text, 'closed'::text])),
  priority text NOT NULL DEFAULT 'medium'::text CHECK (priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'urgent'::text])),
  messages jsonb DEFAULT '[]'::jsonb,
  assigned_to uuid,
  resolved_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT express_support_tickets_pkey PRIMARY KEY (id),
  CONSTRAINT express_support_tickets_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES public.express_sellers(id),
  CONSTRAINT express_support_tickets_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.express_orders(id),
  CONSTRAINT express_support_tickets_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES auth.users(id),
  CONSTRAINT express_support_tickets_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.express_profiles(id)
);
CREATE TABLE public.express_notifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  type text NOT NULL,
  title text NOT NULL,
  body text,
  data jsonb DEFAULT '{}'::jsonb,
  is_read boolean DEFAULT false,
  read_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT express_notifications_pkey PRIMARY KEY (id),
  CONSTRAINT express_notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.express_coupons (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  code text NOT NULL UNIQUE,
  description text,
  discount_type text NOT NULL CHECK (discount_type = ANY (ARRAY['percentage'::text, 'fixed'::text])),
  discount_value numeric NOT NULL,
  min_order_amount numeric DEFAULT 0,
  max_discount_amount numeric,
  usage_limit integer,
  usage_count integer DEFAULT 0,
  user_limit integer DEFAULT 1,
  seller_id uuid,
  category_id uuid,
  valid_from timestamp with time zone NOT NULL DEFAULT now(),
  valid_until timestamp with time zone,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT express_coupons_pkey PRIMARY KEY (id),
  CONSTRAINT express_coupons_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES public.express_sellers(id),
  CONSTRAINT express_coupons_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.express_categories(id)
);
CREATE TABLE public.express_coupon_usage (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  coupon_id uuid NOT NULL,
  user_id uuid NOT NULL,
  order_id uuid,
  discount_amount numeric NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT express_coupon_usage_pkey PRIMARY KEY (id),
  CONSTRAINT express_coupon_usage_coupon_id_fkey FOREIGN KEY (coupon_id) REFERENCES public.express_coupons(id),
  CONSTRAINT express_coupon_usage_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT express_coupon_usage_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.express_orders(id)
);
CREATE TABLE public.express_banners (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  title text NOT NULL,
  subtitle text,
  image_url text NOT NULL,
  link_type text CHECK (link_type = ANY (ARRAY['product'::text, 'category'::text, 'seller'::text, 'url'::text, 'none'::text])),
  link_value text,
  position text DEFAULT 'home_top'::text,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  starts_at timestamp with time zone DEFAULT now(),
  ends_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT express_banners_pkey PRIMARY KEY (id)
);
CREATE TABLE public.express_settings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  key text NOT NULL UNIQUE,
  value jsonb NOT NULL,
  description text,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT express_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.express_payouts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  seller_id uuid NOT NULL,
  amount numeric NOT NULL,
  currency text DEFAULT 'NGN'::text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text])),
  reference text UNIQUE,
  bank_details jsonb,
  processed_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT express_payouts_pkey PRIMARY KEY (id),
  CONSTRAINT express_payouts_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES public.express_sellers(id)
);
CREATE TABLE public.express_review_comments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  review_id uuid NOT NULL,
  user_id uuid NOT NULL,
  comment text NOT NULL,
  is_approved boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT express_review_comments_pkey PRIMARY KEY (id),
  CONSTRAINT express_review_comments_review_id_fkey FOREIGN KEY (review_id) REFERENCES public.express_reviews(id),
  CONSTRAINT express_review_comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.express_profiles(id)
);
CREATE TABLE public.express_chat_conversations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  seller_id uuid NOT NULL,
  last_message text,
  last_message_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT express_chat_conversations_pkey PRIMARY KEY (id),
  CONSTRAINT express_chat_conversations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.express_profiles(id),
  CONSTRAINT express_chat_conversations_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES public.express_sellers(id)
);
CREATE TABLE public.express_chat_messages (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  conversation_id uuid NOT NULL,
  sender_id uuid NOT NULL,
  sender_type text NOT NULL CHECK (sender_type = ANY (ARRAY['user'::text, 'seller'::text])),
  message text NOT NULL,
  message_type text NOT NULL DEFAULT 'text'::text CHECK (message_type = ANY (ARRAY['text'::text, 'image'::text, 'file'::text])),
  is_read boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT express_chat_messages_pkey PRIMARY KEY (id),
  CONSTRAINT express_chat_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.express_chat_conversations(id)
);
CREATE TABLE public.express_ads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  image_url text NOT NULL,
  style text NOT NULL DEFAULT 'banner'::text CHECK (style = ANY (ARRAY['banner'::text, 'card'::text, 'popup'::text, 'carousel'::text, 'story'::text, 'fullscreen'::text, 'sidebar'::text, 'sticky_footer'::text])),
  background_color text DEFAULT '#FFFFFF'::text,
  text_color text DEFAULT '#000000'::text,
  accent_color text DEFAULT '#0B6EFE'::text,
  border_radius integer DEFAULT 12,
  cta_text text DEFAULT 'Shop Now'::text,
  cta_url text,
  discount_badge text,
  discount_color text DEFAULT '#FF6B6B'::text,
  placement text NOT NULL DEFAULT 'home'::text,
  position integer DEFAULT 0,
  is_active boolean DEFAULT true,
  show_on_web boolean DEFAULT true,
  show_on_mobile boolean DEFAULT true,
  start_date timestamp without time zone,
  end_date timestamp without time zone,
  impressions integer DEFAULT 0,
  clicks integer DEFAULT 0,
  created_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  use_image_as_bg boolean DEFAULT true,
  CONSTRAINT express_ads_pkey PRIMARY KEY (id),
  CONSTRAINT express_ads_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.express_seller_statuses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  seller_id uuid NOT NULL,
  media_url text NOT NULL,
  status_text text,
  is_active boolean DEFAULT true,
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '24:00:00'::interval),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  status_type text DEFAULT 'image'::text CHECK (status_type = ANY (ARRAY['image'::text, 'text'::text])),
  background_color text DEFAULT '#FFFFFF'::text,
  gradient_start text,
  gradient_end text,
  text_color text DEFAULT '#000000'::text,
  font_size integer DEFAULT 24,
  CONSTRAINT express_seller_statuses_pkey PRIMARY KEY (id),
  CONSTRAINT express_seller_statuses_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES public.express_sellers(id)
);
CREATE TABLE public.express_follows (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  seller_id uuid NOT NULL,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT express_follows_pkey PRIMARY KEY (id),
  CONSTRAINT express_follows_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT express_follows_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES public.express_sellers(id)
);
CREATE TABLE public.express_device_tokens (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  fcm_token text NOT NULL,
  device_platform text NOT NULL CHECK (device_platform = ANY (ARRAY['android'::text, 'ios'::text, 'web'::text])),
  device_name text,
  app_type text NOT NULL CHECK (app_type = ANY (ARRAY['customer'::text, 'seller'::text, 'admin'::text])),
  is_active boolean DEFAULT true,
  last_used_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT express_device_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT express_device_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.express_flash_sales (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  product_id uuid NOT NULL,
  seller_id uuid NOT NULL,
  flash_price numeric NOT NULL CHECK (flash_price > 0::numeric),
  original_price numeric NOT NULL,
  discount_percentage numeric NOT NULL CHECK (discount_percentage >= 0::numeric AND discount_percentage <= 100::numeric),
  start_time timestamp with time zone NOT NULL,
  end_time timestamp with time zone NOT NULL,
  max_quantity integer CHECK (max_quantity IS NULL OR max_quantity > 0),
  sold_quantity integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT express_flash_sales_pkey PRIMARY KEY (id),
  CONSTRAINT express_flash_sales_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.express_products(id),
  CONSTRAINT express_flash_sales_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES public.express_sellers(id)
);
CREATE TABLE public.app_updates (
  id integer NOT NULL DEFAULT nextval('app_updates_id_seq'::regclass),
  app text NOT NULL,
  latest_version text,
  min_version text,
  force_update boolean DEFAULT false,
  update_message text,
  download_url text,
  release_notes text,
  published_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  platform text,
  CONSTRAINT app_updates_pkey PRIMARY KEY (id)
);